[project]
    id = "your-project-ref"
    name = "your-project-name"

    [database]
    host = "db.your-supabase-url.supabase.co"
    port = 5432
    dbname = "postgres"
    user = "postgres"
    password = "your-db-password"
